language: python
python:
  - "2.7"
os:
  - linux

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pandas numpy scipy matplotlib cython scikit-learn 
  - pip install GPy
  - python setup.py install
script:
  - DP_GP_cluster.py -i test/test.txt -o test/test -p png -n 20 --plot