language: python
python:
  - "2.7"
os:
  - linux
  - osx
    sudo: required
    language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#         brew update
#         brew install python2.7
#         virtualenv venv -p python2.7
#         source venv/bin/activate
        export PATH=$PATH:~/Library/Python/2.7/bin/
    else
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        chmod +x miniconda.sh
        ./miniconda.sh -b
        export PATH=/home/travis/miniconda2/bin:$PATH
        conda update --yes conda
        # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
        sudo rm -rf /dev/shm
        sudo ln -s /run/shm /dev/shm
    fi

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pandas numpy scipy matplotlib cython scikit-learn 
  - pip install GPy
  - python setup.py install
script:
  - DP_GP_cluster.py -i test/test.txt -o test/test -p png -n 20 --plot
  